### ISSUE TITLE
worker crash due to missing property value

### ISSUE THREAD

**Issue by daborg69** [dnaeon/py-vpoller#107]
We have a vm which is in a very goofy state on our VCenter.  It exists in name only, but has no values for host, disks, cpu, etc.  We cannot delete it normally from VCenter.  VMware has given us the fix to correct, but it has been causing zabbix to crash for past couple of days.  Just now figured out it was the vpoller-workers that were crashing and then causing the queue's to build up in Zabbix.  Applied the latest updates as I thought the zabbix queue problem was recently solved, but it still seems to be causing an issue.

However, the specific error causing the vpoller-workers to crash is at line 1745 because the VM has no host assigned to it.  Following is error message.

```bash
Process VPollerWorker-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "build/bdist.linux-x86_64/egg/vpoller/worker.py", line 327, in run
    self.wait_for_tasks()
  File "build/bdist.linux-x86_64/egg/vpoller/worker.py", line 446, in wait_for_tasks
    result = self.process_client_msg(msg)
  File "build/bdist.linux-x86_64/egg/vpoller/worker.py", line 600, in process_client_msg
    result = agent_method['method'](msg)
  File "build/bdist.linux-x86_64/egg/vpoller/agent.py", line 1745, in vm_host_get
    vm_name, vm_host = props['name'], props['runtime.host']
KeyError: 'runtime.host'
```

**Comment by dnaeon** [comment]
The latest release of vPoller handles such exceptions gracefully.

Please update to the latest vPoller release in order to have this issue fixed.

Thanks,
Marin
