### ISSUE TITLE
create zabbix host return error

### ISSUE THREAD

**Issue by holyzhou** [dnaeon/py-vpoller#120]
I'm sorry to bother you , but i think i got a problem when i use zabbix-vsphere-import tool。 
if vm host name have other character ， it will return error

"""
[2015-01-27 11:45:46,550] - INFO - [VirtualMachine@xx.xx.xx.xx] Number of objects to be imported: 17
[2015-01-27 11:45:46,792] - INFO - [VirtualMachine@xx.xx.xx.xx] Creating Zabbix host 'CentOS-5.8-196 （小川）'
Traceback (most recent call last):
  File "zabbix-vsphere-import", line 677, in <module>
    main()
  File "zabbix-vsphere-import", line 670, in main
    zabbix.import_vsphere_vms()
  File "zabbix-vsphere-import", line 392, in import_vsphere_vms
    result = self.zapi.host.create(params)
  File "build/bdist.linux-x86_64/egg/pyzabbix/__init__.py", line 154, in fn
  File "build/bdist.linux-x86_64/egg/pyzabbix/__init__.py", line 129, in do_request
UnicodeEncodeError: 'ascii' codec can't encode characters in position 56-59: ordinal not in range(128)
"""

**Comment by dnaeon** [comment]
This is a Zabbix issue, not vPoller or pyzabbix issue.

Zabbix supports Unicode characters only in the visible name of a host, and the machine name cannot contain unicode at all.

See this issue here for more details.

* https://github.com/dnaeon/py-vpoller/issues/95

Regards,
Marin
