### ISSUE TITLE
After upgrade to new version - spam in log

### ISSUE THREAD

**Issue by takenek** [dnaeon/py-vpoller#124]
Hello
I just upgrade to new 0.3.9-dev version i can`t run vpoller worker got all the time crash:

```python
root@XXXXX:~# /etc/init.d/vpoller-worker start
[2015-02-19 07:57:31,199 - INFO/MainProcess] Starting Worker Manager [0.3.9-dev release]
[2015-02-19 07:57:31,200 - DEBUG/MainProcess] Loading config file /etc/vpoller/vpoller.conf
[2015-02-19 07:57:31,200 - DEBUG/MainProcess] Worker Manager configuration: {'tasks': None, 'cache_maxsize': 0, 'db': '/var/lib/vconnector/vconnector.db', 'cache_enabled': True, 'helpers': ['vpoller.helpers.zabbix', 'vpoller.helpers.czabbix'], 'proxy': 'tcp://localhost:10124', 'cache_housekeeping': 480, 'mgmt': 'tcp://*:10000', 'cache_ttl': 3600}
[2015-02-19 07:57:31,200 - DEBUG/MainProcess] Creating Worker Manager sockets
[2015-02-19 07:57:31,201 - INFO/MainProcess] Starting Worker processes
[2015-02-19 07:57:31,201 - INFO/MainProcess] Concurrency: 16 (processes)
[2015-02-19 07:57:31,203 - INFO/VPollerWorker-1] Worker process is starting
[2015-02-19 07:57:31,203 - INFO/VPollerWorker-2] Worker process is starting
Process VPollerWorker-1:
Traceback (most recent call last):
Process VPollerWorker-2:
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/dist-packages/vpoller/worker.py", line 374, in run
    self.run()
  File "/usr/lib/python2.7/dist-packages/vpoller/worker.py", line 374, in run
    self.load_task_modules()
  File "/usr/lib/python2.7/dist-packages/vpoller/worker.py", line 410, in load_task_modules
    raise VPollerException('No task modules provided')
VPollerException: No task modules provided
    self.load_task_modules()
  File "/usr/lib/python2.7/dist-packages/vpoller/worker.py", line 410, in load_task_modules
    raise VPollerException('No task modules provided')
VPollerException: No task modules provided
[2015-02-19 07:57:31,204 - INFO/VPollerWorker-3] Worker process is starting
[2015-02-19 07:57:31,205 - INFO/VPollerWorker-4] Worker process is starting
Process VPollerWorker-3:
Traceback (most recent call last):
Process VPollerWorker-4:
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/dist-packages/vpoller/worker.py", line 374, in run
    self.run()
  File "/usr/lib/python2.7/dist-packages/vpoller/worker.py", line 374, in run
    self.load_task_modules()
  File "/usr/lib/python2.7/dist-packages/vpoller/worker.py", line 410, in load_task_modules
    raise VPollerException('No task modules provided')
VPollerException: No task modules provided
    self.load_task_modules()
  File "/usr/lib/python2.7/dist-packages/vpoller/worker.py", line 410, in load_task_modules
    raise VPollerException('No task modules provided')
VPollerException: No task modules provided
[2015-02-19 07:57:31,205 - INFO/VPollerWorker-5] Worker process is starting
Process VPollerWorker-5:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/dist-packages/vpoller/worker.py", line 374, in run
    self.load_task_modules()
  File "/usr/lib/python2.7/dist-packages/vpoller/worker.py", line 410, in load_task_modules
    raise VPollerException('No task modules provided')
VPollerException: No task modules provided
[2015-02-19 07:57:31,207 - INFO/VPollerWorker-6] Worker process is starting
Process VPollerWorker-6:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/dist-packages/vpoller/worker.py", line 374, in run
    self.load_task_modules()
  File "/usr/lib/python2.7/dist-packages/vpoller/worker.py", line 410, in load_task_modules
    raise VPollerException('No task modules provided')
VPollerException: No task modules provided
[2015-02-19 07:57:31,208 - INFO/VPollerWorker-7] Worker process is starting
Process VPollerWorker-7:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
[2015-02-19 07:57:31,208 - INFO/VPollerWorker-8] Worker process is starting
Process VPollerWorker-8:
Traceback (most recent call last):
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
  File "/usr/lib/python2.7/dist-packages/vpoller/worker.py", line 374, in run
    self.run()
  File "/usr/lib/python2.7/dist-packages/vpoller/worker.py", line 374, in run
    self.load_task_modules()
  File "/usr/lib/python2.7/dist-packages/vpoller/worker.py", line 410, in load_task_modules
    raise VPollerException('No task modules provided')
    self.load_task_modules()
  File "/usr/lib/python2.7/dist-packages/vpoller/worker.py", line 410, in load_task_modules
VPollerException: No task modules provided
    raise VPollerException('No task modules provided')
VPollerException: No task modules provided
[2015-02-19 07:57:31,209 - INFO/VPollerWorker-9] Worker process is starting
Process VPollerWorker-9:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/dist-packages/vpoller/worker.py", line 374, in run
    self.load_task_modules()
  File "/usr/lib/python2.7/dist-packages/vpoller/worker.py", line 410, in load_task_modules
    raise VPollerException('No task modules provided')
VPollerException: No task modules provided
[2015-02-19 07:57:31,213 - INFO/VPollerWorker-10] Worker process is starting
Process VPollerWorker-10:
[2015-02-19 07:57:31,214 - INFO/VPollerWorker-11] Worker process is starting
Traceback (most recent call last):
[2015-02-19 07:57:31,214 - INFO/VPollerWorker-12] Worker process is starting
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Process VPollerWorker-11:
Process VPollerWorker-12:
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/dist-packages/vpoller/worker.py", line 374, in run
    self.run()
  File "/usr/lib/python2.7/dist-packages/vpoller/worker.py", line 374, in run
    self.run()
  File "/usr/lib/python2.7/dist-packages/vpoller/worker.py", line 374, in run
    self.load_task_modules()
  File "/usr/lib/python2.7/dist-packages/vpoller/worker.py", line 410, in load_task_modules
    self.load_task_modules()
    raise VPollerException('No task modules provided')
  File "/usr/lib/python2.7/dist-packages/vpoller/worker.py", line 410, in load_task_modules
VPollerException: No task modules provided
    raise VPollerException('No task modules provided')
VPollerException: No task modules provided
    self.load_task_modules()
  File "/usr/lib/python2.7/dist-packages/vpoller/worker.py", line 410, in load_task_modules
    raise VPollerException('No task modules provided')
VPollerException: No task modules provided
[2015-02-19 07:57:31,215 - INFO/VPollerWorker-13] Worker process is starting
Process VPollerWorker-13:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/dist-packages/vpoller/worker.py", line 374, in run
    self.load_task_modules()
  File "/usr/lib/python2.7/dist-packages/vpoller/worker.py", line 410, in load_task_modules
    raise VPollerException('No task modules provided')
VPollerException: No task modules provided
[2015-02-19 07:57:31,216 - INFO/VPollerWorker-14] Worker process is starting
Process VPollerWorker-14:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/dist-packages/vpoller/worker.py", line 374, in run
    self.load_task_modules()
  File "/usr/lib/python2.7/dist-packages/vpoller/worker.py", line 410, in load_task_modules
    raise VPollerException('No task modules provided')
VPollerException: No task modules provided
[2015-02-19 07:57:31,217 - INFO/MainProcess] Worker Manager is ready and running
[2015-02-19 07:57:31,217 - INFO/VPollerWorker-15] Worker process is starting
Process VPollerWorker-15:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/dist-packages/vpoller/worker.py", line 374, in run
[2015-02-19 07:57:31,218 - INFO/VPollerWorker-16] Worker process is starting
    self.load_task_modules()
  File "/usr/lib/python2.7/dist-packages/vpoller/worker.py", line 410, in load_task_modules
    raise VPollerException('No task modules provided')
Process VPollerWorker-16:
VPollerException: No task modules provided
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/dist-packages/vpoller/worker.py", line 374, in run
    self.load_task_modules()
  File "/usr/lib/python2.7/dist-packages/vpoller/worker.py", line 410, in load_task_modules
    raise VPollerException('No task modules provided')
VPollerException: No task modules provided
```

**Comment by dnaeon** [comment]
Hi,

Make sure to update your `vpoller.conf` file with the new vPoller settings.

The ``vPoller Worker`` now requires that you specify the task modules that should be loaded.

Note the ``tasks`` option in the ``worker`` section from the config file below.

```ini
[proxy]
frontend     = tcp://*:10123
backend      = tcp://*:10124
mgmt         = tcp://*:9999

[worker]
db           = /var/lib/vconnector/vconnector.db
proxy        = tcp://localhost:10124
mgmt         = tcp://*:10000
helpers      = vpoller.helpers.zabbix, vpoller.helpers.czabbix
tasks        = vpoller.vsphere.tasks

[cache]
enabled      = True
maxsize      = 0
ttl          = 3600
housekeeping = 480
```

Regards,
Marin

**Comment by takenek** [comment]
Hey yes yes i saw this 
Now i got everything but still not working :
[2015-02-19 08:23:37,722 - WARNING/VPollerWorker-11] Task vm.disk.get failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/vpoller/task/decorators.py", line 55, in wrapper
    result = fn(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/vpoller/vsphere/tasks.py", line 2211, in vm_disk_get
    data = agent.vm_disk_discover(msg)
AttributeError: 'VConnector' object has no attribute 'vm_disk_discover'

i use http://jenkins.unix-heaven.org/job/py-vconnector/ws/deb_dist/python-vconnector_0.3.5-1_all.deb version of vconnector.

Thanks

**Comment by dnaeon** [comment]
I've just pushed a fix for this.

You can either upgrade from the latest Git repository or grab the Debian packages from the Jenkins master.

* http://jenkins.unix-heaven.org/job/py-vpoller/ws/deb_dist/
* http://jenkins.unix-heaven.org/job/py-vconnector/ws/deb_dist/

Let me know how it goes.

Thanks,
Marin

**Comment by takenek** [comment]
Hey i use exacly this both files and i got this crash.

http://jenkins.unix-heaven.org/job/py-vconnector/ws/deb_dist/python-vconnector_0.3.5-1_all.deb
http://jenkins.unix-heaven.org/job/py-vpoller/ws/deb_dist/python-vpoller_0.3.9-dev-1_all.deb

Thanks

**Comment by dnaeon** [comment]
The packages from the Jenkins master now contain a fix for this issue, so please grab the packages again and install them :)

**Comment by takenek** [comment]
Change version from python-vpoller_0.3.9-dev-1_all.deb to python-vpoller_0.3.9-dev-2_all.deb
and python-vconnector_0.3.5-1_all.deb to python-vconnector_0.3.5-2_all.deb
Will be easier to know there is a new version 
File name exacly thisa same but is completly other

**Comment by dnaeon** [comment]
Just remove the old versions of vPoller and vConnector and install the new packages.

I will be soon be preparing a release for vPoller and version will be bumped as well.

**Comment by takenek** [comment]
Done – Working good now  No more AttributeError.
Thanks!
