### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by bundaburg** [dnaeon/py-vpoller#125]
Hello,
Receive the following error after upgrade of the vpoller/import tools.

[2015-02-27 09:02:40,885] - ERROR - vPoller task failed: {u'msg': u'Task vm.host.get failed', u'traceback': u'Traceback (most recent call last):\n  File "/usr/lib/python2.7/site-packages/vpoller/task/decorators.py", line 55, in wrapper\n    result = fn(*args, **kwargs)\n  File "/usr/lib/python2.7/site-packages/vpoller/vsphere/tasks.py", line 2128, in vm_host_get\n    vm_name, vm_host = props[\'name\'], props[\'runtime.host\']\nKeyError: \'runtime.host\'\n', u'success': 1}

Thanks!

**Comment by dnaeon** [comment]
Hi,

Please provide the following information:

* What version of vConnector are you using?
* What version of vPoller are you using?
* What version of the `zabbix-vsphere-import` tool are you using?
* Do you get this error for all VMs or just for a particular one?

Thanks,
Marin

**Comment by bundaburg** [comment]
Sorry for the delay:
When testing again to get these versions, it started to work, so must be an issue with the particular host.
