### ISSUE TITLE
Discover VMware Virtual Machines: return unacceptable name of vm

### ISSUE THREAD

**Issue by Nefelim4ag** [dnaeon/py-vpoller#128]
![screenshot from 2015-04-13 15 38 47](https://cloud.githubusercontent.com/assets/3943460/7116150/f49a60f0-e1f7-11e4-93dc-99e0a8c09610.png)
I've try to use zabbix and vPoller and i've get following problems
In autodiscovery host rule, vPoller return vm name as a name and uuid
uuid use () characters and its not acceptable by zabbix

_-_ please fix it, if i don't fix it before _-_

**Comment by dnaeon** [comment]
In your vCenter - are the VMs names in the following form - ``<name>-<uuid>``, because that appears to be the case?

vPoller does not take into account the VM UUID, but just takes the VM name as found in vCenter.

If your VM names in vCenter contain the UUID as well you should probably fix that first.

**Comment by michaelrice** [comment]
Thats how vms are named when there is a vcloud director involved.

**Comment by Nefelim4ag** [comment]
Oh, sorry guys, my error.

**Comment by Nefelim4ag** [comment]
I'm again very sorry, but can anyone suggest where i can add filter in vpoller for cut uuids from vm name?

**Comment by dnaeon** [comment]
@Nefelim4ag vPoller doesn't have any support for filtering names of vSphere objects.

vPoller just takes what it gets from the vSphere API and returns it. 

It is actually Zabbix that doesn't allow you to set the name that vPoller returns for it, so there's nothing we can do in vPoller in order to have this issue fixed.

One possible solution to your issue might be to actually use the `{HOST.NAME}` macro, which is basically the host visible name in Zabbix and that field allows for any characters to be used. The error you get is because your `{HOST.HOST}` macro contains the `( )` characters, which are not allowed there.

I'll see if I can get a patch prepared for the ``zabbix-vsphere-import`` tool, as this seems like a more appropriate location for such a fix and not vPoller itself. Maybe we can also add a filter-based feature in ``zabbix-vsphere-import`` tool, so we can control the names being imported into Zabbix.

**Comment by dnaeon** [comment]
@Nefelim4ag Please follow these steps in order to import your VMs into Zabbix and have them monitored by vPoller.

* Remove all VMs from Zabbix that were discovered by the previous discovery rules
* Update your Zabbix templates with the latest ones from https://github.com/dnaeon/py-vpoller/tree/master/extra/zabbix/templates/vpoller-templates-native
* Make sure that vPoller is up and running
* Make sure that the Zabbix Template discovery rules for VMs are disabled
* Update the ``Template VMware vSphere Virtual Machine - vPoller Native`` template and where you see the ``{HOST.HOST}`` macro replace it with ``{HOST.NAME}``
* Clone the vPoller repository from Github

```bash
$ git clone https://github.com/dnaeon/py-vpoller.git
```

* Apply the patch for ``zabbix-vsphere-import`` tool from https://gist.github.com/dnaeon/0acec0a6d9c79b084290#file-vpoller-issue-128-patch

```bash
$ cd py-vpoller
$ curl https://gist.githubusercontent.com/dnaeon/0acec0a6d9c79b084290/raw/b18198c3ea828f024e46538deba49079217e3bfc/vpoller-issue-128.patch -o vpoller-issue-128.patch
$ git apply vpoller-issue-128.patch
```

* Create a ``zabbix-vsphere-import.yaml`` file (you can an example file in https://github.com/dnaeon/py-vpoller/tree/master/extra/zabbix/vsphere-import)
* Run the ``zabbix-vsphere-import`` with your config file that you've prepared in the previous step. This would create the VMs in Zabbix with machine name set to ``<VM>`` and visible name set to ``<VM> (UUID)``.
* Confirm that Zabbix is now successfully monitoring your VMs.

Let me know how it goes.

**Comment by Nefelim4ag** [comment]
Hey, I'm very sorry for long delay -.- i was busy

i've try you instruction but i get:
root@debian:/tmp/py-vpoller# ./extra/zabbix/vsphere-import/zabbix-vsphere-import -f ../zabbix-vsphere-import.yaml
[2015-05-25 16:47:21,784] - INFO - JSON-RPC Server Endpoint: http://172.20.73.26/zabbix/api_jsonrpc.php
[2015-05-25 16:47:21,784] - INFO - Connecting to Zabbix server at http://172.20.73.26/zabbix
[2015-05-25 16:47:21,787] - INFO - Starting new HTTP connection (1): 172.20.73.26
[2015-05-25 16:47:21,809] - INFO - Zabbix API version is 2.4.5
[2015-05-25 16:47:21,809] - INFO - [Datacenter@vc.example.corp] Importing objects to Zabbix
[2015-05-25 16:47:21,956] - INFO - [Datacenter@vc.example.corp] Objects are in sync with Zabbix
[2015-05-25 16:47:21,957] - INFO - [ClusterComputeResource@vc.example.corp] Importing objects to Zabbix
[2015-05-25 16:47:22,061] - INFO - [ClusterComputeResource@vc.example.corp] Objects are in sync with Zabbix
[2015-05-25 16:47:22,061] - INFO - [HostSystem@vc.example.corp] Importing objects to Zabbix
[2015-05-25 16:47:22,232] - INFO - [HostSystem@vc.example.corp] Objects are in sync with Zabbix
[2015-05-25 16:47:22,234] - INFO - [VirtualMachine@vc.example.corp] Importing objects to Zabbix
[2015-05-25 16:47:22,551] - INFO - [VirtualMachinevc.example.corp] Number of objects to be imported: 450
[2015-05-25 16:47:22,567] - INFO - [VirtualMachine@vc.example.corp] Creating Zabbix host 'FusionDb (9187fe10-d19c-4bb9-8f9d-933f98a10649)'
Traceback (most recent call last):
  File "./extra/zabbix/vsphere-import/zabbix-vsphere-import", line 763, in <module>
    main()
  File "./extra/zabbix/vsphere-import/zabbix-vsphere-import", line 756, in main
    zabbix.import_vsphere_vms()
  File "./extra/zabbix/vsphere-import/zabbix-vsphere-import", line 443, in import_vsphere_vms
    machine_name, visible_name = host.split(sep=' ')
TypeError: split() takes no keyword arguments


Can i miss something?

**Comment by dnaeon** [comment]
@Nefelim4ag 

Here's an updated patch, please get this patch instead and apply it. This should fix the exception that you've seen.

https://gist.github.com/dnaeon/eca835909b61b3a54427

**Comment by Nefelim4ag** [comment]
[2015-05-26 17:52:09,145] - INFO - [VirtualMachine@vc.itransition.corp] Creating Zabbix host 'Debian 8 Server (9538fada-a2b2-4c52-a291-b05dbd48e071)'
Traceback (most recent call last):
  File "./extra/zabbix/vsphere-import/zabbix-vsphere-import", line 763, in <module>
    main()
  File "./extra/zabbix/vsphere-import/zabbix-vsphere-import", line 756, in main
    zabbix.import_vsphere_vms()
  File "./extra/zabbix/vsphere-import/zabbix-vsphere-import", line 443, in import_vsphere_vms
    machine_name, visible_name = host.split(' ')
ValueError: too many values to unpack

It create more hosts, but also failed after several (8 hosts)

**Comment by dnaeon** [comment]
Oh, you have VMs with multiple spaces in their name...

Here's an updated patch, please try it out:

 - https://gist.github.com/dnaeon/eca835909b61b3a54427
