### ISSUE TITLE
vpoller not support Chinese ?

### ISSUE THREAD

**Issue by tnndlbmu** [dnaeon/py-vpoller#130]
Hi Marin,
When i used ./zabbix-vsphere-import -f /usr/lib/zabbix/zabbix-vsphere-import.yaml 
output shows below:
[2015-04-24 17:14:39,469] - INFO - [Datacenter@192.168.192.3] Creating Zabbix host '上海'
[2015-04-24 17:14:39,470] - INFO - Resetting dropped connection: 10.100.22.38
Traceback (most recent call last):
  File "./zabbix-vsphere-import", line 757, in <module>
    main()
  File "./zabbix-vsphere-import", line 747, in main
    zabbix.import_vsphere_datacenters()
  File "./zabbix-vsphere-import", line 224, in import_vsphere_datacenters
    result = self.zapi.host.create(params)
  File "build/bdist.linux-x86_64/egg/pyzabbix/__init__.py", line 156, in fn
  File "build/bdist.linux-x86_64/egg/pyzabbix/__init__.py", line 131, in do_request
UnicodeEncodeError: 'ascii' codec can't encode characters in position 41-42: ordinal not in range(128)

Thanks for help.

**Comment by tnndlbmu** [comment]
Hi Marin,
i modified the zabbix-vsphere-import see below in the beginning:
import sys
reload(sys)
sys.setdefaultencoding('utf-8')

seems working fine now.

**Comment by dnaeon** [comment]
Yep, unicode support is not that great in vPoller currently, but simple fixes like the one you did work.

You might want to send a pull request with your changes, so they could be added to the script. 

Thanks,
Marin
