### ISSUE TITLE
VConnector DB file not present on install

### ISSUE THREAD

**Issue by stephenh1991** [dnaeon/py-vpoller#139]
Hi,

New to vpoller but it will not init after I install via pip or via source, error I get:

[root@INF-MGTZABBIX01 /]# vconnector-cli init
Traceback (most recent call last):
  File "/usr/bin/vconnector-cli", line 182, in <module>
    main()
  File "/usr/bin/vconnector-cli", line 161, in main
    init_db(args['--database'])
  File "/usr/bin/vconnector-cli", line 50, in init_db
    db = VConnectorDatabase(db)
  File "/usr/lib/python2.6/site-packages/vconnector/core.py", line 433, in __init__
    self.conn = sqlite3.connect(self.db)
sqlite3.OperationalError: unable to open database file

Thanks!

**Comment by dnaeon** [comment]
Hey,

You are using Python 2.6, and vPoller needs at least Python 2.7 or 3.x

Please upgrade your Python version.

Thanks,
Marin

**Comment by indreek** [comment]
I have the same problem, except python is v2.7

/etc/vpoller$ sudo vconnector-cli init
Traceback (most recent call last):
  File "/usr/local/bin/vconnector-cli", line 182, in <module>
    main()
  File "/usr/local/bin/vconnector-cli", line 161, in main
    init_db(args['--database'])
  File "/usr/local/bin/vconnector-cli", line 50, in init_db
    db = VConnectorDatabase(db)
  File "/usr/local/lib/python2.7/dist-packages/vconnector/core.py", line 460, in __init__
    self.conn = sqlite3.connect(self.db)
sqlite3.OperationalError: unable to open database file

**Comment by jeffnic** [comment]
Same problem for me:
(venv)[root@dev-smd py-vconnector-master]# vconnector-cli init
Cannot initialize database: unable to open database file

I resolved by running this command:
(venv)[root@dev-smd py-vconnector-master]# mkdir /var/lib/vconnector

Versions:
CentOS Linux release 7.1.1503 (Core)
Python: 2.75
docopt==0.6.2
pyvmomi==6.7.0
tabulate==0.8.2
vconnector==0.5.0
vpoller==0.7.0

**Comment by dnaeon** [comment]
Correct, you’ll need tp create any parent directories yourself, as vconnector does not do that for you.
