### ISSUE TITLE
ZMQError

### ISSUE THREAD

**Issue by papezg** [dnaeon/py-vpoller#149]
Hi!

I'm new to vpoller and I need a bit of a help.
I installed vpoller and prerequisites as instrucdet by excellent documentation but when O run vpoller-worker I get following error:

root@zabbix:~/zeromq4-x# vpoller-worker -e http://localhost:10123 status
Traceback (most recent call last):
  File "/usr/local/bin/vpoller-worker", line 5, in <module>
    pkg_resources.run_script('vpoller==0.5.8', 'vpoller-worker')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 528, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1401, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/vpoller-0.5.8-py2.7.egg/EGG-INFO/scripts/vpoller-worker", line 138, in <module>

  File "/usr/local/lib/python2.7/dist-packages/vpoller-0.5.8-py2.7.egg/EGG-INFO/scripts/vpoller-worker", line 135, in main

  File "/usr/local/lib/python2.7/dist-packages/vpoller-0.5.8-py2.7.egg/EGG-INFO/scripts/vpoller-worker", line 86, in status

  File "build/bdist.linux-x86_64/egg/vpoller/client.py", line 85, in run
  File "socket.pyx", line 516, in zmq.backend.cython.socket.Socket.connect (zmq/backend/cython/socket.c:5118)
zmq.error.ZMQError: Protocol not supported

**Comment by papezg** [comment]
Stupid me. got wrong port!
Close this

**Comment by dnaeon** [comment]
Glad you figured it out! :)
