### ISSUE TITLE
vPoller worker stops working after trying to receive performance metric for disconnected host

### ISSUE THREAD

**Issue by olfway** [dnaeon/py-vpoller#161]
worker stops working after that exception:

```
[2015-11-25 19:03:54,170 - INFO/VPollerWorker-2] [v-center] Retrieving performance metric net.received.kiloBytesPerSecond.average for host-disconnected.example.org
Process VPollerWorker-2:
Traceback (most recent call last):
  File "/opt/vpoller/lib/vpoller/worker.py", line 483, in run_helper
    result = h.run()
  File "/opt/vpoller/lib/vpoller/helpers/czabbix.py", line 69, in run
    result = helper.run()
  File "/opt/vpoller/lib/vpoller/helpers/zabbix.py", line 141, in run
    result = self.methods[self.method]()
  File "/opt/vpoller/lib/vpoller/helpers/zabbix.py", line 162, in zabbix_item_value
    result = self.data['result'][-1]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/opt/vpoller/lib/vpoller/worker.py", line 382, in run
    self.wait_for_tasks()
  File "/opt/vpoller/lib/vpoller/worker.py", line 528, in wait_for_tasks
    data=result
  File "/opt/vpoller/lib/vpoller/worker.py", line 485, in run_helper
    logger.warning('Helper module raised an exception: %s', e.message)
AttributeError: 'IndexError' object has no attribute 'message'
```

**Comment by olfway** [comment]
btw, self.data in this case is {'result': [], 'success': 0, 'msg': 'Successfully retrieved performance metrics'}

**Comment by dnaeon** [comment]
@olfway vPoller should not stop working after such an exception, because they are handled gracefully.

Is the host that you are polling  from is indeed disconnected?

**Comment by olfway** [comment]
Did you noticed there was another exception during handling the first one?

Before that exception there were log entries from VPollerWorker-1 / VPollerWorker-2
after exception on VPollerWorker-1 there were entries only from VPollerWorker-2,
after same performance metric was hit VPollerWorker2 it was crashed too
and zabbix started to mark items unsupported on timeouts

yep, what esxi host registered in vsphere but now disconnected

also, i replaced numeric performance metric id (148 and 149 afair) in template, with "net.received.kiloBytesPerSecond.average" and net.transmitted...
it seems that numeric id doesn't works now

**Comment by dnaeon** [comment]
Please grab the latest release of vPoller which fixes these issues.
