### ISSUE TITLE
VPoller exception during housekeeping

### ISSUE THREAD

**Issue by olfway** [dnaeon/py-vpoller#162]
Noticed an exception in vpoller log, i guess it shouldn't?

2015-11-26 03:19:05,476 - INFO/VPollerWorker-1] Starting cache housekeeper [171 item(s) in cache]
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 1180, in run
    self.function(*self.args, **self.kwargs)
  File "/opt/vpoller/lib/vconnector/cache.py", line 148, in _housekeeper
    for item in self._cache.values():
RuntimeError: OrderedDict mutated during iteration

**Comment by dnaeon** [comment]
Fixed in https://github.com/dnaeon/py-vconnector/commit/09378a46ac83f778766213f20c48ccebc95ae7a2

Please grab the latest version of vPoller and vConnector.
