### ISSUE TITLE
centos 7: problem starting vpoller-worker

### ISSUE THREAD

**Issue by kippie538** [dnaeon/py-vpoller#165]
After starting the vpoller-worker is get following output

[2015-12-09 09:00:48,818 - INFO/MainProcess] Starting Worker processes
[2015-12-09 09:00:48,818 - INFO/MainProcess] Concurrency: 1 (processes)
[2015-12-09 09:00:48,819 - INFO/MainProcess] Worker Manager is ready and running
[2015-12-09 09:00:48,821 - INFO/VPollerWorker-1] Worker process is starting
[2015-12-09 09:00:48,821 - INFO/VPollerWorker-1] Loading task module vpoller.vsphere.tasks
[2015-12-09 09:00:48,823 - INFO/VPollerWorker-1] Loading helper module vpoller.helpers.zabbix
[2015-12-09 09:00:48,824 - INFO/VPollerWorker-1] Loading helper module vpoller.helpers.czabbix
[2015-12-09 09:00:48,824 - INFO/VPollerWorker-1] Creating Worker sockets
Process VPollerWorker-1:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "build/bdist.linux-x86_64/egg/vpoller/worker.py", line 377, in run
    self.create_agents()
  File "build/bdist.linux-x86_64/egg/vpoller/worker.py", line 605, in create_agents
    cache_housekeeping=self.config.get('cache_housekeeping')
  File "build/bdist.linux-x86_64/egg/vconnector/core.py", line 96, in __init__
    default_context = ssl.create_default_context()
AttributeError: 'module' object has no attribute 'create_default_context'

I use Centos 7 
pip freeze | egrep 'pyvmomi|vpoller|vconnector|requests'
pyvmomi==6.0.0
requests==2.8.1
vconnector==0.4.3
vpoller==0.6.1

**Comment by dnaeon** [comment]
Please update vconnector to 0.4.4 version and you should be okay.
