### ISSUE TITLE
vpoller-worker died with exception

### ISSUE THREAD

**Issue by olfway** [dnaeon/py-vpoller#172]
Hello!

I've run vpoller-client -V v-center -m vm.get --name 'vm' -p runtime.host
and worker died with:
```
Feb  2 12:41:21 zabbix vpoller-worker[8288]: Process VPollerWorker-1:
Feb  2 12:41:21 zabbix vpoller-worker[8288]: Traceback (most recent call last):
Feb  2 12:41:21 zabbix vpoller-worker[8288]: File "/usr/lib/python3.4/multiprocessing/process.py", line 254, in _bootstrap
Feb  2 12:41:21 zabbix vpoller-worker[8288]: self.run()
Feb  2 12:41:21 zabbix vpoller-worker[8288]: File "/usr/lib/python3/dist-packages/vpoller/worker.py", line 382, in run
Feb  2 12:41:21 zabbix vpoller-worker[8288]: self.wait_for_tasks()
Feb  2 12:41:21 zabbix vpoller-worker[8288]: File "/usr/lib/python3/dist-packages/vpoller/worker.py", line 533, in wait_for_tasks
Feb  2 12:41:21 zabbix vpoller-worker[8288]: data = json.dumps(result, ensure_ascii=False)
Feb  2 12:41:21 zabbix vpoller-worker[8288]: File "/usr/lib/python3.4/json/__init__.py", line 237, in dumps
Feb  2 12:41:21 zabbix vpoller-worker[8288]: **kw).encode(obj)
Feb  2 12:41:21 zabbix vpoller-worker[8288]: File "/usr/lib/python3.4/json/encoder.py", line 192, in encode
Feb  2 12:41:21 zabbix vpoller-worker[8288]: chunks = self.iterencode(o, _one_shot=True)
Feb  2 12:41:21 zabbix vpoller-worker[8288]: File "/usr/lib/python3.4/json/encoder.py", line 250, in iterencode
Feb  2 12:41:21 zabbix vpoller-worker[8288]: return _iterencode(o, 0)
Feb  2 12:41:21 zabbix vpoller-worker[8288]: File "/usr/lib/python3.4/json/encoder.py", line 173, in default
Feb  2 12:41:21 zabbix vpoller-worker[8288]: raise TypeError(repr(o) + " is not JSON serializable")
Feb  2 12:41:21 zabbix vpoller-worker[8288]: TypeError: 'vim.HostSystem:host-941' is not JSON serializable
```

**Comment by dnaeon** [comment]
Hey,

Use the `vm.host.get` instead of `vm.get` vPoller method for this purpose.

 - http://vpoller.readthedocs.org/en/latest/methods.html

Thanks,
Marin
