### ISSUE TITLE
vpoller-worker again died on exception

### ISSUE THREAD

**Issue by olfway** [dnaeon/py-vpoller#175]
Hello!

Something went wrong on request, but because of bad exception handling vpoller-worker died and wasn't restarted:
```
20783 ?        Ssl    0:00 /usr/bin/python3 /usr/bin/vpoller-worker --concurrency 3 --file /etc/vpoller/vpoller.conf start
20789 ?        Z    386:02  \_ [vpoller-worker] <defunct>
20790 ?        Z    382:51  \_ [vpoller-worker] <defunct>
20791 ?        Z     72:44  \_ [vpoller-worker] <defunct>
```

Exception:
```
Feb  7 07:36:38 zabbix vpoller-worker[20783]: Process VPollerWorker-1:
Feb  7 07:36:38 zabbix vpoller-worker[20783]: Traceback (most recent call last):
Feb  7 07:36:38 zabbix vpoller-worker[20783]: File "/usr/lib/python3/dist-packages/vpoller/worker.py", line 483, in run_helper
Feb  7 07:36:38 zabbix vpoller-worker[20783]: result = h.run()
Feb  7 07:36:38 zabbix vpoller-worker[20783]: File "/usr/lib/python3/dist-packages/vpoller/helpers/czabbix.py", line 69, in run
Feb  7 07:36:38 zabbix vpoller-worker[20783]: result = helper.run()
Feb  7 07:36:38 zabbix vpoller-worker[20783]: File "/usr/lib/python3/dist-packages/vpoller/helpers/zabbix.py", line 141, in run
Feb  7 07:36:38 zabbix vpoller-worker[20783]: result = self.methods[self.method]()
Feb  7 07:36:38 zabbix vpoller-worker[20783]: File "/usr/lib/python3/dist-packages/vpoller/helpers/zabbix.py", line 162, in zabbix_item_value
Feb  7 07:36:38 zabbix vpoller-worker[20783]: result = self.data['result'][-1]
Feb  7 07:36:38 zabbix vpoller-worker[20783]: IndexError: list index out of range
```

During exception handling you tries to add log message:
logger.warning('Helper module raised an exception: %s', e.message)
but there is no "message" attribute, so another exception, that kills vpoller-worker:
```
Feb  7 07:36:38 zabbix vpoller-worker[20783]: During handling of the above exception, another exception occurred:
Feb  7 07:36:38 zabbix vpoller-worker[20783]: Traceback (most recent call last):
Feb  7 07:36:38 zabbix vpoller-worker[20783]: File "/usr/lib/python3.4/multiprocessing/process.py", line 254, in _bootstrap
Feb  7 07:36:38 zabbix vpoller-worker[20783]: self.run()
Feb  7 07:36:38 zabbix vpoller-worker[20783]: File "/usr/lib/python3/dist-packages/vpoller/worker.py", line 382, in run
Feb  7 07:36:38 zabbix vpoller-worker[20783]: self.wait_for_tasks()
Feb  7 07:36:38 zabbix vpoller-worker[20783]: File "/usr/lib/python3/dist-packages/vpoller/worker.py", line 528, in wait_for_tasks
Feb  7 07:36:38 zabbix vpoller-worker[20783]: data=result
Feb  7 07:36:38 zabbix vpoller-worker[20783]: File "/usr/lib/python3/dist-packages/vpoller/worker.py", line 485, in run_helper
Feb  7 07:36:38 zabbix vpoller-worker[20783]: logger.warning('Helper module raised an exception: %s', e.message)
Feb  7 07:36:38 zabbix vpoller-worker[20783]: AttributeError: 'IndexError' object has no attribute 'message'
```

**Comment by dnaeon** [comment]
Hey @olfway,

Can you please try the latest version of vPoller? I've just pushed a fix for this.

Thanks,
Marin

**Comment by olfway** [comment]
Thanks, I've updated vpoller, will look for exceptions/errors in logs
