### ISSUE TITLE
SSL Errror

### ISSUE THREAD

**Issue by bundaburg** [dnaeon/py-vpoller#179]
Hi
I have just installed vpoller on a new EL7 system within a virtualenv, all up to date with python 2.7.

Upon testing I still get the SSL certificate error.  I read that the pyvmomi 6.0 was required, but I have this installed.

Requirement already satisfied (use --upgrade to upgrade): vpoller in ./vpoller-venv/lib/python2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): pyzmq>=14.3.1 in ./vpoller-venv/lib/python2.7/site-packages (from vpoller)
Requirement already satisfied (use --upgrade to upgrade): docopt>=0.6.2 in ./vpoller-venv/lib/python2.7/site-packages (from vpoller)
Requirement already satisfied (use --upgrade to upgrade): pyvmomi>=6.0.0 in ./vpoller-venv/lib/python2.7/site-packages (from vpoller)
Requirement already satisfied (use --upgrade to upgrade): vconnector>=0.4.3 in ./vpoller-venv/lib/python2.7/site-packages (from vpoller)
Requirement already satisfied (use --upgrade to upgrade): requests>=2.3.0 in ./vpoller-venv/lib/python2.7/site-packages (from pyvmomi>=6.0.0->vpoller)
Requirement already satisfied (use --upgrade to upgrade): six>=1.7.3 in ./vpoller-venv/lib/python2.7/site-packages (from pyvmomi>=6.0.0->vpoller)
Requirement already satisfied (use --upgrade to upgrade): tabulate>=0.7.3 in ./vpoller-venv/lib/python2.7/site-packages (from vconnector>=0.4.3->vpoller)

Log:

/virtualenv/vpoller-venv/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:315: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/virtualenv/vpoller-venv/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
[2016-03-25 16:27:40,223 - ERROR/VPollerWorker-2] Cannot connect to x.com: [Errno 1] _ssl.c:510: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
[2016-03-25 16:27:40,225 - WARNING/VPollerWorker-2] Task datastore.discover failed: Traceback (most recent call last):
  File "/virtualenv/vpoller-venv/lib/python2.7/site-packages/vpoller/task/decorators.py", line 55, in wrapper
    result = fn(*args, **kwargs)
  File "/virtualenv/vpoller-venv/lib/python2.7/site-packages/vpoller/vsphere/tasks.py", line 2517, in datastore_discover
    obj_type=pyVmomi.vim.Datastore
  File "/virtualenv/vpoller-venv/lib/python2.7/site-packages/vpoller/vsphere/tasks.py", line 65, in _discover_objects
    view_ref = agent.get_container_view(obj_type=[obj_type])
  File "/virtualenv/vpoller-venv/lib/python2.7/site-packages/vconnector/core.py", line 347, in get_container_view
    container = self.si.content.rootFolder
  File "/virtualenv/vpoller-venv/lib/python2.7/site-packages/vconnector/core.py", line 123, in si
    self.connect()
  File "/virtualenv/vpoller-venv/lib/python2.7/site-packages/vconnector/core.py", line 159, in connect
    sslContext=self.ssl_context,
  File "/virtualenv/vpoller-venv/lib/python2.7/site-packages/pyVim/connect.py", line 663, in SmartConnect
    sslContext)
  File "/virtualenv/vpoller-venv/lib/python2.7/site-packages/pyVim/connect.py", line 552, in __FindSupportedVersion
    sslContext)
  File "/virtualenv/vpoller-venv/lib/python2.7/site-packages/pyVim/connect.py", line 472, in __GetServiceVersionDescription
    tree = __GetElementTreeFromUrl(url, sslContext)
  File "/virtualenv/vpoller-venv/lib/python2.7/site-packages/pyVim/connect.py", line 440, in __GetElementTreeFromUrl
    sock = requests.get(url)
  File "/virtualenv/vpoller-venv/lib/python2.7/site-packages/requests/api.py", line 67, in get
    return request('get', url, params=params, **kwargs)
  File "/virtualenv/vpoller-venv/lib/python2.7/site-packages/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/virtualenv/vpoller-venv/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/virtualenv/vpoller-venv/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/virtualenv/vpoller-venv/lib/python2.7/site-packages/requests/adapters.py", line 447, in send
    raise SSLError(e, request=request)
SSLError: [Errno 1] _ssl.c:510: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed

Any ideas?

Thanks,

**Comment by dnaeon** [comment]
What version of Python are you running with?

**Comment by bundaburg** [comment]
Running version 2.7.8 
Thanks!

**Comment by dnaeon** [comment]
You should switch to at least version 2.7.9.

Pyvmomi no longer supports older versions than 2.7.9, that is why you get
this error.
