### ISSUE TITLE
vpoller-worker AttributeError: 'module' object has no attribute 'SSLContext'

### ISSUE THREAD

**Issue by takenek** [dnaeon/py-vpoller#180]
Hello
Because You drop Debian package i just compile from source and got problem when i start vpoller-worker i get error:

root@WIZJA2:~# vpoller-worker start
[2016-03-30 08:47:23,105 - INFO/MainProcess] Starting Worker Manager [0.6.1 release]
[2016-03-30 08:47:23,107 - INFO/MainProcess] Starting Worker processes
[2016-03-30 08:47:23,107 - INFO/MainProcess] Concurrency: 16 (processes)
[2016-03-30 08:47:23,109 - INFO/VPollerWorker-1] Worker process is starting
[2016-03-30 08:47:23,109 - INFO/VPollerWorker-2] Worker process is starting
[2016-03-30 08:47:23,109 - INFO/VPollerWorker-1] Loading task module vpoller.vsphere.tasks
[2016-03-30 08:47:23,109 - INFO/VPollerWorker-2] Loading task module vpoller.vsphere.tasks
[2016-03-30 08:47:23,110 - INFO/VPollerWorker-3] Worker process is starting
[2016-03-30 08:47:23,111 - INFO/VPollerWorker-3] Loading task module vpoller.vsphere.tasks
[2016-03-30 08:47:23,112 - INFO/VPollerWorker-2] Loading helper module vpoller.helpers.zabbix
[2016-03-30 08:47:23,112 - INFO/VPollerWorker-4] Worker process is starting
[2016-03-30 08:47:23,112 - INFO/VPollerWorker-1] Loading helper module vpoller.helpers.zabbix
[2016-03-30 08:47:23,112 - INFO/VPollerWorker-4] Loading task module vpoller.vsphere.tasks
[2016-03-30 08:47:23,112 - INFO/VPollerWorker-2] Loading helper module vpoller.helpers.czabbix
[2016-03-30 08:47:23,112 - INFO/VPollerWorker-2] Creating Worker sockets
[2016-03-30 08:47:23,113 - INFO/VPollerWorker-1] Loading helper module vpoller.helpers.czabbix
[2016-03-30 08:47:23,113 - INFO/VPollerWorker-3] Loading helper module vpoller.helpers.zabbix
[2016-03-30 08:47:23,113 - INFO/VPollerWorker-1] Creating Worker sockets
[2016-03-30 08:47:23,113 - INFO/VPollerWorker-5] Worker process is starting
[2016-03-30 08:47:23,113 - INFO/VPollerWorker-3] Loading helper module vpoller.helpers.czabbix
[2016-03-30 08:47:23,113 - INFO/VPollerWorker-5] Loading task module vpoller.vsphere.tasks
[2016-03-30 08:47:23,113 - INFO/VPollerWorker-3] Creating Worker sockets
Process VPollerWorker-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
[2016-03-30 08:47:23,114 - INFO/VPollerWorker-6] Worker process is starting
  File "/usr/local/lib/python2.7/dist-packages/vpoller-0.6.1-py2.7.egg/vpoller/worker.py", line 377, in run
[2016-03-30 08:47:23,115 - INFO/VPollerWorker-6] Loading task module vpoller.vsphere.tasks
    self.create_agents()
[2016-03-30 08:47:23,115 - INFO/VPollerWorker-4] Loading helper module vpoller.helpers.zabbix
  File "/usr/local/lib/python2.7/dist-packages/vpoller-0.6.1-py2.7.egg/vpoller/worker.py", line 605, in create_agents
    cache_housekeeping=self.config.get('cache_housekeeping')
  File "/usr/lib/python2.7/dist-packages/vconnector/core.py", line 97, in __init__
Process VPollerWorker-1:
Traceback (most recent call last):
Process VPollerWorker-3:
    ctx = ssl.SSLContext(ssl.PROTOCOL_TLSv1)
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
AttributeError: 'module' object has no attribute 'SSLContext'
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/vpoller-0.6.1-py2.7.egg/vpoller/worker.py", line 377, in run
[2016-03-30 08:47:23,115 - INFO/VPollerWorker-4] Loading helper module vpoller.helpers.czabbix
[2016-03-30 08:47:23,115 - INFO/VPollerWorker-7] Worker process is starting
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/vpoller-0.6.1-py2.7.egg/vpoller/worker.py", line 377, in run
    self.create_agents()
[2016-03-30 08:47:23,116 - INFO/VPollerWorker-7] Loading task module vpoller.vsphere.tasks
  File "/usr/local/lib/python2.7/dist-packages/vpoller-0.6.1-py2.7.egg/vpoller/worker.py", line 605, in create_agents
    cache_housekeeping=self.config.get('cache_housekeeping')
  File "/usr/lib/python2.7/dist-packages/vconnector/core.py", line 97, in __init__
[2016-03-30 08:47:23,116 - INFO/VPollerWorker-4] Creating Worker sockets
    self.create_agents()
    ctx = ssl.SSLContext(ssl.PROTOCOL_TLSv1)
  File "/usr/local/lib/python2.7/dist-packages/vpoller-0.6.1-py2.7.egg/vpoller/worker.py", line 605, in create_agents
AttributeError: 'module' object has no attribute 'SSLContext'
    cache_housekeeping=self.config.get('cache_housekeeping')
  File "/usr/lib/python2.7/dist-packages/vconnector/core.py", line 97, in __init__
[2016-03-30 08:47:23,116 - INFO/VPollerWorker-5] Loading helper module vpoller.helpers.zabbix
    ctx = ssl.SSLContext(ssl.PROTOCOL_TLSv1)
AttributeError: 'module' object has no attribute 'SSLContext'
[2016-03-30 08:47:23,117 - INFO/VPollerWorker-5] Loading helper module vpoller.helpers.czabbix
[2016-03-30 08:47:23,117 - INFO/VPollerWorker-5] Creating Worker sockets
[2016-03-30 08:47:23,118 - INFO/VPollerWorker-6] Loading helper module vpoller.helpers.zabbix
Process VPollerWorker-4:
[2016-03-30 08:47:23,117 - INFO/VPollerWorker-8] Worker process is starting
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
[2016-03-30 08:47:23,118 - INFO/VPollerWorker-6] Loading helper module vpoller.helpers.czabbix
[2016-03-30 08:47:23,118 - INFO/VPollerWorker-8] Loading task module vpoller.vsphere.tasks
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/vpoller-0.6.1-py2.7.egg/vpoller/worker.py", line 377, in run
[2016-03-30 08:47:23,118 - INFO/VPollerWorker-6] Creating Worker sockets
    self.create_agents()
  File "/usr/local/lib/python2.7/dist-packages/vpoller-0.6.1-py2.7.egg/vpoller/worker.py", line 605, in create_agents
    cache_housekeeping=self.config.get('cache_housekeeping')
[2016-03-30 08:47:23,118 - INFO/VPollerWorker-9] Worker process is starting
  File "/usr/lib/python2.7/dist-packages/vconnector/core.py", line 97, in __init__
[2016-03-30 08:47:23,119 - INFO/VPollerWorker-7] Loading helper module vpoller.helpers.zabbix
[2016-03-30 08:47:23,119 - INFO/VPollerWorker-9] Loading task module vpoller.vsphere.tasks
Process VPollerWorker-5:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    ctx = ssl.SSLContext(ssl.PROTOCOL_TLSv1)
AttributeError: 'module' object has no attribute 'SSLContext'
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/vpoller-0.6.1-py2.7.egg/vpoller/worker.py", line 377, in run
[2016-03-30 08:47:23,119 - INFO/VPollerWorker-7] Loading helper module vpoller.helpers.czabbix
    self.create_agents()
  File "/usr/local/lib/python2.7/dist-packages/vpoller-0.6.1-py2.7.egg/vpoller/worker.py", line 605, in create_agents
    cache_housekeeping=self.config.get('cache_housekeeping')
  File "/usr/lib/python2.7/dist-packages/vconnector/core.py", line 97, in __init__
[2016-03-30 08:47:23,119 - INFO/VPollerWorker-7] Creating Worker sockets
    ctx = ssl.SSLContext(ssl.PROTOCOL_TLSv1)
AttributeError: 'module' object has no attribute 'SSLContext'
[2016-03-30 08:47:23,121 - INFO/VPollerWorker-9] Loading helper module vpoller.helpers.zabbix
Process VPollerWorker-6:
Traceback (most recent call last):
[2016-03-30 08:47:23,121 - INFO/VPollerWorker-8] Loading helper module vpoller.helpers.zabbix
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
[2016-03-30 08:47:23,121 - INFO/VPollerWorker-9] Loading helper module vpoller.helpers.czabbix
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/vpoller-0.6.1-py2.7.egg/vpoller/worker.py", line 377, in run
[2016-03-30 08:47:23,121 - INFO/VPollerWorker-9] Creating Worker sockets
Process VPollerWorker-7:
[2016-03-30 08:47:23,122 - INFO/VPollerWorker-8] Loading helper module vpoller.helpers.czabbix
Traceback (most recent call last):
[2016-03-30 08:47:23,121 - INFO/VPollerWorker-10] Worker process is starting
    self.create_agents()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
  File "/usr/local/lib/python2.7/dist-packages/vpoller-0.6.1-py2.7.egg/vpoller/worker.py", line 605, in create_agents
    cache_housekeeping=self.config.get('cache_housekeeping')
  File "/usr/lib/python2.7/dist-packages/vconnector/core.py", line 97, in __init__
[2016-03-30 08:47:23,122 - INFO/VPollerWorker-10] Loading task module vpoller.vsphere.tasks
    self.run()
[2016-03-30 08:47:23,122 - INFO/VPollerWorker-8] Creating Worker sockets
  File "/usr/local/lib/python2.7/dist-packages/vpoller-0.6.1-py2.7.egg/vpoller/worker.py", line 377, in run
    ctx = ssl.SSLContext(ssl.PROTOCOL_TLSv1)
AttributeError: 'module' object has no attribute 'SSLContext'
    self.create_agents()
  File "/usr/local/lib/python2.7/dist-packages/vpoller-0.6.1-py2.7.egg/vpoller/worker.py", line 605, in create_agents
    cache_housekeeping=self.config.get('cache_housekeeping')
  File "/usr/lib/python2.7/dist-packages/vconnector/core.py", line 97, in __init__
    ctx = ssl.SSLContext(ssl.PROTOCOL_TLSv1)
AttributeError: 'module' object has no attribute 'SSLContext'
[2016-03-30 08:47:23,123 - INFO/VPollerWorker-11] Worker process is starting
[2016-03-30 08:47:23,123 - INFO/VPollerWorker-11] Loading task module vpoller.vsphere.tasks
Process VPollerWorker-9:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/vpoller-0.6.1-py2.7.egg/vpoller/worker.py", line 377, in run
    self.create_agents()
  File "/usr/local/lib/python2.7/dist-packages/vpoller-0.6.1-py2.7.egg/vpoller/worker.py", line 605, in create_agents
    cache_housekeeping=self.config.get('cache_housekeeping')
  File "/usr/lib/python2.7/dist-packages/vconnector/core.py", line 97, in __init__
    ctx = ssl.SSLContext(ssl.PROTOCOL_TLSv1)
AttributeError: 'module' object has no attribute 'SSLContext'
Process VPollerWorker-8:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
[2016-03-30 08:47:23,124 - INFO/VPollerWorker-12] Worker process is starting
    self.run()
[2016-03-30 08:47:23,125 - INFO/VPollerWorker-12] Loading task module vpoller.vsphere.tasks
  File "/usr/local/lib/python2.7/dist-packages/vpoller-0.6.1-py2.7.egg/vpoller/worker.py", line 377, in run
    self.create_agents()
  File "/usr/local/lib/python2.7/dist-packages/vpoller-0.6.1-py2.7.egg/vpoller/worker.py", line 605, in create_agents
    cache_housekeeping=self.config.get('cache_housekeeping')
  File "/usr/lib/python2.7/dist-packages/vconnector/core.py", line 97, in __init__
    ctx = ssl.SSLContext(ssl.PROTOCOL_TLSv1)
AttributeError: 'module' object has no attribute 'SSLContext'
[2016-03-30 08:47:23,126 - INFO/VPollerWorker-10] Loading helper module vpoller.helpers.zabbix
[2016-03-30 08:47:23,126 - INFO/VPollerWorker-11] Loading helper module vpoller.helpers.zabbix
[2016-03-30 08:47:23,126 - INFO/VPollerWorker-11] Loading helper module vpoller.helpers.czabbix
[2016-03-30 08:47:23,126 - INFO/VPollerWorker-10] Loading helper module vpoller.helpers.czabbix
[2016-03-30 08:47:23,126 - INFO/VPollerWorker-13] Worker process is starting
[2016-03-30 08:47:23,126 - INFO/VPollerWorker-13] Loading task module vpoller.vsphere.tasks
[2016-03-30 08:47:23,126 - INFO/VPollerWorker-11] Creating Worker sockets
[2016-03-30 08:47:23,126 - INFO/VPollerWorker-10] Creating Worker sockets
[2016-03-30 08:47:23,127 - INFO/VPollerWorker-12] Loading helper module vpoller.helpers.zabbix
[2016-03-30 08:47:23,127 - INFO/VPollerWorker-12] Loading helper module vpoller.helpers.czabbix
[2016-03-30 08:47:23,127 - INFO/VPollerWorker-12] Creating Worker sockets
[2016-03-30 08:47:23,127 - INFO/VPollerWorker-14] Worker process is starting
[2016-03-30 08:47:23,127 - INFO/VPollerWorker-14] Loading task module vpoller.vsphere.tasks
Process VPollerWorker-10:
Process VPollerWorker-11:
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
[2016-03-30 08:47:23,128 - INFO/VPollerWorker-13] Loading helper module vpoller.helpers.zabbix
    self.run()
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/vpoller-0.6.1-py2.7.egg/vpoller/worker.py", line 377, in run
  File "/usr/local/lib/python2.7/dist-packages/vpoller-0.6.1-py2.7.egg/vpoller/worker.py", line 377, in run
    self.create_agents()
    self.create_agents()
  File "/usr/local/lib/python2.7/dist-packages/vpoller-0.6.1-py2.7.egg/vpoller/worker.py", line 605, in create_agents
  File "/usr/local/lib/python2.7/dist-packages/vpoller-0.6.1-py2.7.egg/vpoller/worker.py", line 605, in create_agents
    cache_housekeeping=self.config.get('cache_housekeeping')
    cache_housekeeping=self.config.get('cache_housekeeping')
  File "/usr/lib/python2.7/dist-packages/vconnector/core.py", line 97, in __init__
  File "/usr/lib/python2.7/dist-packages/vconnector/core.py", line 97, in __init__
[2016-03-30 08:47:23,128 - INFO/VPollerWorker-13] Loading helper module vpoller.helpers.czabbix
Process VPollerWorker-12:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    ctx = ssl.SSLContext(ssl.PROTOCOL_TLSv1)
    ctx = ssl.SSLContext(ssl.PROTOCOL_TLSv1)
[2016-03-30 08:47:23,128 - INFO/VPollerWorker-15] Worker process is starting
AttributeError: 'module' object has no attribute 'SSLContext'
AttributeError: 'module' object has no attribute 'SSLContext'
[2016-03-30 08:47:23,129 - INFO/VPollerWorker-15] Loading task module vpoller.vsphere.tasks
[2016-03-30 08:47:23,129 - INFO/MainProcess] Worker Manager is ready and running
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/vpoller-0.6.1-py2.7.egg/vpoller/worker.py", line 377, in run
[2016-03-30 08:47:23,129 - INFO/VPollerWorker-13] Creating Worker sockets
    self.create_agents()
  File "/usr/local/lib/python2.7/dist-packages/vpoller-0.6.1-py2.7.egg/vpoller/worker.py", line 605, in create_agents
    cache_housekeeping=self.config.get('cache_housekeeping')
  File "/usr/lib/python2.7/dist-packages/vconnector/core.py", line 97, in __init__
    ctx = ssl.SSLContext(ssl.PROTOCOL_TLSv1)
[2016-03-30 08:47:23,129 - INFO/VPollerWorker-14] Loading helper module vpoller.helpers.zabbix
AttributeError: 'module' object has no attribute 'SSLContext'
[2016-03-30 08:47:23,129 - INFO/VPollerWorker-16] Worker process is starting
[2016-03-30 08:47:23,129 - INFO/VPollerWorker-14] Loading helper module vpoller.helpers.czabbix
[2016-03-30 08:47:23,130 - INFO/VPollerWorker-16] Loading task module vpoller.vsphere.tasks
[2016-03-30 08:47:23,130 - INFO/VPollerWorker-14] Creating Worker sockets
Process VPollerWorker-13:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/vpoller-0.6.1-py2.7.egg/vpoller/worker.py", line 377, in run
    self.create_agents()
  File "/usr/local/lib/python2.7/dist-packages/vpoller-0.6.1-py2.7.egg/vpoller/worker.py", line 605, in create_agents
    cache_housekeeping=self.config.get('cache_housekeeping')
  File "/usr/lib/python2.7/dist-packages/vconnector/core.py", line 97, in __init__
    ctx = ssl.SSLContext(ssl.PROTOCOL_TLSv1)
AttributeError: 'module' object has no attribute 'SSLContext'
[2016-03-30 08:47:23,131 - INFO/VPollerWorker-15] Loading helper module vpoller.helpers.zabbix
[2016-03-30 08:47:23,131 - INFO/VPollerWorker-16] Loading helper module vpoller.helpers.zabbix
[2016-03-30 08:47:23,132 - INFO/VPollerWorker-15] Loading helper module vpoller.helpers.czabbix
Process VPollerWorker-14:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
[2016-03-30 08:47:23,132 - INFO/VPollerWorker-16] Loading helper module vpoller.helpers.czabbix
    self.run()
[2016-03-30 08:47:23,132 - INFO/VPollerWorker-15] Creating Worker sockets
[2016-03-30 08:47:23,132 - INFO/VPollerWorker-16] Creating Worker sockets
  File "/usr/local/lib/python2.7/dist-packages/vpoller-0.6.1-py2.7.egg/vpoller/worker.py", line 377, in run
    self.create_agents()
  File "/usr/local/lib/python2.7/dist-packages/vpoller-0.6.1-py2.7.egg/vpoller/worker.py", line 605, in create_agents
    cache_housekeeping=self.config.get('cache_housekeeping')
  File "/usr/lib/python2.7/dist-packages/vconnector/core.py", line 97, in __init__
    ctx = ssl.SSLContext(ssl.PROTOCOL_TLSv1)
AttributeError: 'module' object has no attribute 'SSLContext'
Process VPollerWorker-16:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/vpoller-0.6.1-py2.7.egg/vpoller/worker.py", line 377, in run
    self.create_agents()
  File "/usr/local/lib/python2.7/dist-packages/vpoller-0.6.1-py2.7.egg/vpoller/worker.py", line 605, in create_agents
    cache_housekeeping=self.config.get('cache_housekeeping')
  File "/usr/lib/python2.7/dist-packages/vconnector/core.py", line 97, in __init__
    ctx = ssl.SSLContext(ssl.PROTOCOL_TLSv1)
AttributeError: 'module' object has no attribute 'SSLContext'
Process VPollerWorker-15:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/vpoller-0.6.1-py2.7.egg/vpoller/worker.py", line 377, in run
    self.create_agents()
  File "/usr/local/lib/python2.7/dist-packages/vpoller-0.6.1-py2.7.egg/vpoller/worker.py", line 605, in create_agents
    cache_housekeeping=self.config.get('cache_housekeeping')
  File "/usr/lib/python2.7/dist-packages/vconnector/core.py", line 97, in __init__
    ctx = ssl.SSLContext(ssl.PROTOCOL_TLSv1)
AttributeError: 'module' object has no attribute 'SSLContext'

**Comment by dnaeon** [comment]
Please switch to at least Python version 2.7.9.

pyVmomi has dropped support for Python versions prior to 2.7.9, so has vPoller as well.

**Comment by mholttech** [comment]
I've been trying to figure this out, I can't find a way to get Python 2.7.9 or newer installed on Ubuntu 14.04 without breaking anything

**Comment by mholttech** [comment]
I got it worked out:

````
sudo apt-get install python3 python3-pip python3-jinja2
sudo pip3 install vpoller
````
