### ISSUE TITLE
Debian 7.9 (wheezy) and python 3.2.3 SSL3_GET_SERVER_CERTIFICATE

### ISSUE THREAD

**Issue by boffen** [dnaeon/py-vpoller#183]
We are facing a problem with vpoller and SSL connections. 
Since it is required to have python> 2.7.9 and Debian 7.9 does not have packages for python 2.7.9 I tried to use python3.2 instead.

# pip-3.2 freeze | egrep 'pyvmomi|vpoller|vconnector|requests'
pyvmomi==6.0.0
requests==2.9.1
vconnector==0.4.6
vpoller==0.6.1

see output from vpoller-worker when I try to connect below.

Any suggestions? 

[2016-04-01 16:27:42,364 - INFO/VPollerWorker-1] Connecting vSphere Agent to REMOVED-HOSTNAME
[2016-04-01 16:27:42,376 - INFO/VPollerWorker-1] Starting new HTTPS connection (1): REMOVED-HOSTNAME
[2016-04-01 16:27:42,397 - ERROR/VPollerWorker-1] Cannot connect to REMOVED-HOSTNAME: [Errno 1] _ssl.c:392: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
[2016-04-01 16:27:42,403 - WARNING/VPollerWorker-1] Task datacenter.alarm.get failed: Traceback (most recent call last):
  File "/usr/local/lib/python3.2/dist-packages/requests/packages/urllib3/connectionpool.py", line 559, in urlopen
    body=body, headers=headers)
  File "/usr/local/lib/python3.2/dist-packages/requests/packages/urllib3/connectionpool.py", line 345, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.2/dist-packages/requests/packages/urllib3/connectionpool.py", line 784, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.2/dist-packages/requests/packages/urllib3/connection.py", line 252, in connect
    ssl_version=resolved_ssl_version)
  File "/usr/local/lib/python3.2/dist-packages/requests/packages/urllib3/util/ssl_.py", line 305, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.2/ssl.py", line 189, in wrap_socket
    _context=self)
  File "/usr/lib/python3.2/ssl.py", line 276, in __init__
    raise x
  File "/usr/lib/python3.2/ssl.py", line 272, in __init__
    self.do_handshake()
  File "/usr/lib/python3.2/ssl.py", line 451, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [Errno 1] _ssl.c:392: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.2/dist-packages/requests/adapters.py", line 376, in send
    timeout=timeout
  File "/usr/local/lib/python3.2/dist-packages/requests/packages/urllib3/connectionpool.py", line 588, in urlopen
    raise SSLError(e)
requests.packages.urllib3.exceptions.SSLError: [Errno 1] _ssl.c:392: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.2/dist-packages/vpoller/vsphere/tasks.py", line 124, in _get_object_properties
    obj_type=obj_type
  File "/usr/local/lib/python3.2/dist-packages/vconnector/core.py", line 412, in get_object_by_property
    view_ref = self.get_container_view(obj_type=[obj_type])
  File "/usr/local/lib/python3.2/dist-packages/vconnector/core.py", line 347, in get_container_view
    container = self.si.content.rootFolder
  File "/usr/local/lib/python3.2/dist-packages/vconnector/core.py", line 123, in si
    self.connect()
  File "/usr/local/lib/python3.2/dist-packages/vconnector/core.py", line 159, in connect
    sslContext=self.ssl_context,
  File "/usr/local/lib/python3.2/dist-packages/pyVim/connect.py", line 663, in SmartConnect
    sslContext)
  File "/usr/local/lib/python3.2/dist-packages/pyVim/connect.py", line 552, in __FindSupportedVersion
    sslContext)
  File "/usr/local/lib/python3.2/dist-packages/pyVim/connect.py", line 472, in __GetServiceVersionDescription
    tree = __GetElementTreeFromUrl(url, sslContext)
  File "/usr/local/lib/python3.2/dist-packages/pyVim/connect.py", line 440, in __GetElementTreeFromUrl
    sock = requests.get(url)
  File "/usr/local/lib/python3.2/dist-packages/requests/api.py", line 67, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.2/dist-packages/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.2/dist-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.2/dist-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.2/dist-packages/requests/adapters.py", line 447, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [Errno 1] _ssl.c:392: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.2/dist-packages/vpoller/task/decorators.py", line 55, in wrapper
    result = fn(*args, **kwargs)
  File "/usr/local/lib/python3.2/dist-packages/vpoller/vsphere/tasks.py", line 1081, in datacenter_alarm_get
    obj_property_value=msg['name']
  File "/usr/local/lib/python3.2/dist-packages/vpoller/vsphere/tasks.py", line 248, in _object_alarm_get
    obj_property_value=obj_property_value
  File "/usr/local/lib/python3.2/dist-packages/vpoller/vsphere/tasks.py", line 127, in _get_object_properties
    return {'success': 1, 'msg': 'Cannot collect properties: {}'.format(e.message)}
AttributeError: 'SSLError' object has no attribute 'message'

**Comment by mholttech** [comment]
here's what I did for a ubuntu machine running vpoller, maybe this will help you:

````
apt-get -y install gcc g++ supervisor python3 python3-pip python3-jinja2
sudo pip3 install vpoller pyyaml pyzabbix
sudo mkdir -p /etc/vpoller /var/run/vpoller /var/log/vpoller /var/lib/vconnector /var/log/vconnector
sudo nano /etc/vpoller/vpoller.conf
````
vpoller.conf
````
[proxy]
frontend     = tcp://*:10123
backend      = tcp://*:10124
mgmt         = tcp://*:9999

[worker]
db           = /var/lib/vconnector/vconnector.db
proxy        = tcp://localhost:10124
mgmt         = tcp://*:10001
helpers      = vpoller.helpers.zabbix, vpoller.helpers.czabbix
tasks        = vpoller.vsphere.tasks

[cache]
enabled      = False
maxsize      = 0
ttl          = 0
housekeeping = 480
````

````
libzmq_dir=$( mktemp -d /tmp/libzmq.XXXXXX )
git clone https://github.com/zeromq/zeromq4-x.git ${libzmq_dir}
cd ${libzmq_dir}
./autogen.sh
./configure
make && make install && make clean
ldconfig


vconnector-cli init
vconnector-cli -H vc01.test.com -U vpoller@vsphere.local -P VPass1! add
vconnector-cli -H vc01.test.com enable
````

TEST
````
vpoller-client --method datastore.discover --vsphere-host ladbtwelve.ladbnet.local --helper vpoller.helpers.zabbix
````

**Comment by mholttech** [comment]
/etc/supervisor/conf.d/vpoller.conf
````
    [program:vpoller-proxy]
    command=/usr/local/bin/vpoller-proxy start
    redirect_stderr=true
    stdout_logfile=/var/log/vpoller/vpoller-proxy.log
    autostart=true
    ;user=myusername
    stopsignal=INT

    [program:vpoller-worker]
    command=/usr/local/bin/vpoller-worker --concurrency 20 start
    redirect_stderr=true
    stdout_logfile=/var/log/vpoller/vpoller-worker.log
    autostart=true
    ;user=myusername
    stopsignal=INT
````

````
supervisorctl reread
supervisorctl start vpoller-proxy
supervisorctl start vpoller-worker
````

Test
````
vpoller-client --method datastore.discover --vsphere-host vc01.test.com --helper vpoller.helpers.zabbix
````

**Comment by dnaeon** [comment]
This should be fixed in latest vPoller.
