### ISSUE TITLE
vpoller-worker defunct

### ISSUE THREAD

**Issue by mholttech** [dnaeon/py-vpoller#185]
Hey,

So when I run vpoller-worker with supervisorctl it starts going defunct after a few minutes and supervisorctl doesn't restore it.  when I execute the command in terminal though there doesn't seem to be any issues.

Here's my supervisor conf:

````
command=/usr/local/bin/vpoller-proxy start
redirect_stderr=true
stdout_logfile=/var/log/vpoller/vpoller-proxy.log
autostart=true
;user=myusername
stopsignal=INT

[program:vpoller-worker]
command=/usr/local/bin/vpoller-worker --concurrency 20 start
redirect_stderr=true
stdout_logfile=/var/log/vpoller/vpoller-worker.log
autostart=true
;user=myusername
stopsignal=INT
````

vpoller-worker.log
````
Process VPollerWorker-4:
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/vpoller/worker.py", line 483, in run_helper
    result = h.run()
  File "/usr/local/lib/python3.4/dist-packages/vpoller/helpers/czabbix.py", line 69, in run
    result = helper.run()
  File "/usr/local/lib/python3.4/dist-packages/vpoller/helpers/zabbix.py", line 141, in run
    result = self.methods[self.method]()
  File "/usr/local/lib/python3.4/dist-packages/vpoller/helpers/zabbix.py", line 162, in zabbix_item_value
    result = self.data['result'][-1]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.4/dist-packages/vpoller/worker.py", line 382, in run
    self.wait_for_tasks()
  File "/usr/local/lib/python3.4/dist-packages/vpoller/worker.py", line 528, in wait_for_tasks
    data=result
  File "/usr/local/lib/python3.4/dist-packages/vpoller/worker.py", line 485, in run_helper
    logger.warning('Helper module raised an exception: %s', e.message)
AttributeError: 'IndexError' object has no attribute 'message'
Process VPollerWorker-8:
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/vpoller/worker.py", line 483, in run_helper
    result = h.run()
  File "/usr/local/lib/python3.4/dist-packages/vpoller/helpers/czabbix.py", line 69, in run
    result = helper.run()
  File "/usr/local/lib/python3.4/dist-packages/vpoller/helpers/zabbix.py", line 141, in run
    result = self.methods[self.method]()
  File "/usr/local/lib/python3.4/dist-packages/vpoller/helpers/zabbix.py", line 162, in zabbix_item_value
    result = self.data['result'][-1]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.4/dist-packages/vpoller/worker.py", line 382, in run
    self.wait_for_tasks()
  File "/usr/local/lib/python3.4/dist-packages/vpoller/worker.py", line 528, in wait_for_tasks
    data=result
  File "/usr/local/lib/python3.4/dist-packages/vpoller/worker.py", line 485, in run_helper
    logger.warning('Helper module raised an exception: %s', e.message)
AttributeError: 'IndexError' object has no attribute 'message'
````

**Comment by mholttech** [comment]
Update: looks like running in terminal it is slowly faulting as wellas well

**Comment by Bonn93** [comment]
20 threads is seems pretty high, why don't you drop it to match your system thread count and see if it becomes more stable?

Python does register hyperthreads from the system too, so you can easily identify a safe number with;

python >>>
>>> import multiprocessing
>>> print multiprocessing.cpu_count()

**Comment by mholttech** [comment]
When I only run 4 agents (the number of cores my VM has) it isn't processing the volume of checks that I have fast enough (htop shows processing 25-30 checks per second)

**Comment by dnaeon** [comment]
Hey @mholttech,

I believe you are running with an older version of vPoller.

This issue has been fixed in #175.

Can you please update vPoller and try again?

Thanks,
Marin

**Comment by mholttech** [comment]
I'm running v0.6.1 installed through pip

**Comment by dnaeon** [comment]
Can you please try the latest version from the Git repo?
