### ISSUE TITLE
SSLEOFError: EOF occurred in violation of protocol

### ISSUE THREAD

**Issue by darrynv** [dnaeon/py-vpoller#261]
Zabbix 3.4.15
Vpoller 0.7.1
vCenter 6.7 Update 1

`[2018-12-21 10:22:56,541 - WARNING/VPollerWorker-4] Task host.perf.metric.get failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/vpoller/task/decorators.py", line 55, in wrapper
    result = fn(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/vpoller/vsphere/tasks.py", line 1462, in host_perf_metric_get
    obj_type=pyVmomi.vim.HostSystem
  File "/usr/lib/python2.7/site-packages/vconnector/core.py", line 411, in get_object_by_property
    view_ref = self.get_container_view(obj_type=[obj_type])
  File "/usr/lib/python2.7/site-packages/vconnector/core.py", line 346, in get_container_view
    container = self.si.content.rootFolder
  File "/usr/lib/python2.7/site-packages/vconnector/core.py", line 121, in si
    self.connect()
  File "/usr/lib/python2.7/site-packages/vconnector/core.py", line 158, in connect
    sslContext=self.ssl_context,
  File "/usr/lib/python2.7/site-packages/pyVim/connect.py", line 836, in SmartConnect
    sslContext)
  File "/usr/lib/python2.7/site-packages/pyVim/connect.py", line 718, in __FindSupportedVersion
    sslContext)
  File "/usr/lib/python2.7/site-packages/pyVim/connect.py", line 638, in __GetServiceVersionDescription
    path + "/vimServiceVersions.xml", sslContext)
  File "/usr/lib/python2.7/site-packages/pyVim/connect.py", line 604, in __GetElementTree
    conn.request("GET", path)
  File "/usr/lib64/python2.7/httplib.py", line 1041, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python2.7/httplib.py", line 1075, in _send_request
    self.endheaders(body)
  File "/usr/lib64/python2.7/httplib.py", line 1037, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python2.7/httplib.py", line 881, in _send_output
    self.send(msg)
  File "/usr/lib64/python2.7/httplib.py", line 843, in send
    self.connect()
  File "/usr/lib64/python2.7/httplib.py", line 1260, in connect
    server_hostname=sni_hostname)
  File "/usr/lib64/python2.7/ssl.py", line 348, in wrap_socket
    _context=self)
  File "/usr/lib64/python2.7/ssl.py", line 609, in __init__
    self.do_handshake()
  File "/usr/lib64/python2.7/ssl.py", line 831, in do_handshake
    self._sslobj.do_handshake()
SSLEOFError: EOF occurred in violation of protocol (_ssl.c:579)

[2018-12-21 10:22:56,542 - INFO/VPollerWorker-4] [serverxyz00001.broken.com] Retrieving properties for serverxyz00001.broken.com managed object of type vim.HostSystem
`

**Comment by cliobrando** [comment]
Hi,
I solved the problem upgrading all the python components, with the following command:
`pip install --upgrade requests vconnector vpoller pyvmomi`
and then restarted the workers.
I think that upgrading pyvmomi is enough to make vpoller work again, but decided to upgrade the 4 components just to make sure.
