### ISSUE TITLE
Error starting vpoller-worker

### ISSUE THREAD

**Issue by Cenzooo** [dnaeon/py-vpoller#265]
Hello,

I have installed vconnector and vpoller as guided in documentation. This are versions of programs:
vconnector-cli --version : 0.5.3
vpoller-worker --version: 0.7.3
python --version : Python 2.7.12

I can successfully start vpoller-proxy, but when i try to start vpoller-worker following error appears:

Traceback (most recent call last):
  File "/usr/local/bin/vpoller-worker", line 4, in <module>
    __import__('pkg_resources').run_script('vpoller==0.7.3', 'vpoller-worker')
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 661, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1448, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/vpoller-0.7.3-py2.7.egg/EGG-INFO/scripts/vpoller-worker", line 138, in <module>
    
  File "/usr/local/lib/python2.7/dist-packages/vpoller-0.7.3-py2.7.egg/EGG-INFO/scripts/vpoller-worker", line 130, in main
    
  File "/usr/local/lib/python2.7/dist-packages/vpoller-0.7.3-py2.7.egg/EGG-INFO/scripts/vpoller-worker", line 62, in start
    
  File "build/bdist.linux-x86_64/egg/vpoller/worker.py", line 118, in start
  File "build/bdist.linux-x86_64/egg/vpoller/worker.py", line 230, in create_sockets
  File "zmq/backend/cython/socket.pyx", line 547, in zmq.backend.cython.socket.Socket.bind
  File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc

Any ideas?

**Comment by Cenzooo** [comment]
On the other server I did the same, difference is only I have python version 3 there, and I get this error:


Traceback (most recent call last):
  File "/usr/local/bin/vpoller-worker", line 4, in <module>
    __import__('pkg_resources').run_script('vpoller==0.7.3', 'vpoller-worker')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1429, in run_script
    .format(**locals()),
pkg_resources.ResolutionError: Script 'scripts/vpoller-worker' not found in metadata at '/usr/local/lib/python3.6/dist-packages/vpoller-0.7.3.egg-info'

**Comment by Cenzooo** [comment]
Hello,

we solved the problem by reinstalling everything... There is another issue now mentioned in : https://github.com/dnaeon/py-vpoller/issues/264 so I will close this one.
